### ISSUE TITLE
When I visit 'http://localhost:4001/video', it will emerge 2 records in  Mongodb (video)

### ISSUE THREAD

**Issue by BobJackson** [bootstrapping-microservices/chapter-5#8]
When I enter "http://localhost:4001/video" in my chrome,I find this:

![image](https://user-images.githubusercontent.com/15266708/111907148-0728c180-8a8f-11eb-98cb-28d6c30a1cf1.png)

![image](https://user-images.githubusercontent.com/15266708/111906670-a00a0d80-8a8c-11eb-86fd-56afa611544a.png)

The first request's type is **document**, the second is **media**, but  both of them are same url.
I guess the twice requests lead to this result.But I don't know why it produces twice different type request.

Note: I was curious to find the reason, until I saw the console output:

![image](https://user-images.githubusercontent.com/15266708/111907053-9f727680-8a8e-11eb-9c0c-07b1e37443ef.png)

**Comment by ashleydavis** [comment]
I think it's because a browser will usually probe for streaming video using HTTP HEAD request followed by a HTTP GET request which are both handled by the HTTP GET request handler in Express, so it can look like the request is coming through twice.

I actually have a blog post up for more advanced video streaming:

https://www.the-data-wrangler.com/video-streaming-in-safari

That's necessary for Safari, but it can also help with video streaming for other browser's like Chrome.

Hope that helps!
